# Generated by Django 4.2.7 on 2026-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_address_productorder_productorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select products jo is offer mein dikhane hain",
                related_name="offer_products",
                to="api.product",
            ),
        ),
    ]
