# Generated by Django 4.2.7 on 2026-05-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_emailotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("splash_bg_url", models.URLField(blank=True, null=True)),
                ("splash_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
            },
        ),
    ]
